// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: ticket/v1/ticket.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ticket_IssuePriority int32

const (
	Ticket_HIGH   Ticket_IssuePriority = 0
	Ticket_MEDIUM Ticket_IssuePriority = 1
	Ticket_LOW    Ticket_IssuePriority = 2
)

// Enum value maps for Ticket_IssuePriority.
var (
	Ticket_IssuePriority_name = map[int32]string{
		0: "HIGH",
		1: "MEDIUM",
		2: "LOW",
	}
	Ticket_IssuePriority_value = map[string]int32{
		"HIGH":   0,
		"MEDIUM": 1,
		"LOW":    2,
	}
)

func (x Ticket_IssuePriority) Enum() *Ticket_IssuePriority {
	p := new(Ticket_IssuePriority)
	*p = x
	return p
}

func (x Ticket_IssuePriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ticket_IssuePriority) Descriptor() protoreflect.EnumDescriptor {
	return file_ticket_v1_ticket_proto_enumTypes[0].Descriptor()
}

func (Ticket_IssuePriority) Type() protoreflect.EnumType {
	return &file_ticket_v1_ticket_proto_enumTypes[0]
}

func (x Ticket_IssuePriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ticket_IssuePriority.Descriptor instead.
func (Ticket_IssuePriority) EnumDescriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_proto_rawDescGZIP(), []int{0, 0}
}

type Ticket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId   string                 `protobuf:"bytes,2,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	CreatorName string                 `protobuf:"bytes,3,opt,name=creatorName,proto3" json:"creatorName,omitempty"`
	Issues      []*Ticket_Issue        `protobuf:"bytes,4,rep,name=issues,proto3" json:"issues,omitempty"`
	CreateTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_v1_ticket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Ticket) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *Ticket) GetIssues() []*Ticket_Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *Ticket) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type Ticket_Issue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Priority    Ticket_IssuePriority `protobuf:"varint,2,opt,name=priority,proto3,enum=student.Ticket_IssuePriority" json:"priority,omitempty"`
	Description string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Assignee    string               `protobuf:"bytes,4,opt,name=assignee,proto3" json:"assignee,omitempty"`
}

func (x *Ticket_Issue) Reset() {
	*x = Ticket_Issue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_v1_ticket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ticket_Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket_Issue) ProtoMessage() {}

func (x *Ticket_Issue) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket_Issue.ProtoReflect.Descriptor instead.
func (*Ticket_Issue) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Ticket_Issue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket_Issue) GetPriority() Ticket_IssuePriority {
	if x != nil {
		return x.Priority
	}
	return Ticket_HIGH
}

func (x *Ticket_Issue) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ticket_Issue) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

var File_ticket_v1_ticket_proto protoreflect.FileDescriptor

var file_ticket_v1_ticket_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x86, 0x03, 0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a,
	0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x49,
	0x73, 0x73, 0x75, 0x65, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x90, 0x01, 0x0a, 0x05, 0x49, 0x73, 0x73,
	0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x39, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x50, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x22, 0x2e, 0x0a, 0x0d, 0x49,
	0x73, 0x73, 0x75, 0x65, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x08, 0x0a, 0x04,
	0x48, 0x49, 0x47, 0x48, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10, 0x02, 0x42, 0x41, 0x0a, 0x19, 0x63,
	0x6f, 0x6d, 0x2e, 0x73, 0x62, 0x61, 0x69, 0x74, 0x6d, 0x61, 0x6e, 0x2e, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x0b, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xa2, 0x02, 0x03, 0x52, 0x54, 0x47, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ticket_v1_ticket_proto_rawDescOnce sync.Once
	file_ticket_v1_ticket_proto_rawDescData = file_ticket_v1_ticket_proto_rawDesc
)

func file_ticket_v1_ticket_proto_rawDescGZIP() []byte {
	file_ticket_v1_ticket_proto_rawDescOnce.Do(func() {
		file_ticket_v1_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(file_ticket_v1_ticket_proto_rawDescData)
	})
	return file_ticket_v1_ticket_proto_rawDescData
}

var file_ticket_v1_ticket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ticket_v1_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ticket_v1_ticket_proto_goTypes = []interface{}{
	(Ticket_IssuePriority)(0),     // 0: student.Ticket.IssuePriority
	(*Ticket)(nil),                // 1: student.Ticket
	(*Ticket_Issue)(nil),          // 2: student.Ticket.Issue
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_ticket_v1_ticket_proto_depIdxs = []int32{
	2, // 0: student.Ticket.issues:type_name -> student.Ticket.Issue
	3, // 1: student.Ticket.createTime:type_name -> google.protobuf.Timestamp
	0, // 2: student.Ticket.Issue.priority:type_name -> student.Ticket.IssuePriority
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ticket_v1_ticket_proto_init() }
func file_ticket_v1_ticket_proto_init() {
	if File_ticket_v1_ticket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ticket_v1_ticket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ticket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_v1_ticket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ticket_Issue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ticket_v1_ticket_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ticket_v1_ticket_proto_goTypes,
		DependencyIndexes: file_ticket_v1_ticket_proto_depIdxs,
		EnumInfos:         file_ticket_v1_ticket_proto_enumTypes,
		MessageInfos:      file_ticket_v1_ticket_proto_msgTypes,
	}.Build()
	File_ticket_v1_ticket_proto = out.File
	file_ticket_v1_ticket_proto_rawDesc = nil
	file_ticket_v1_ticket_proto_goTypes = nil
	file_ticket_v1_ticket_proto_depIdxs = nil
}
